src/App.tsx
src/AppEntry.tsx

https://issues.redhat.com/browse/RHCLOUD-21132

External documentation added

---

src/App.tsx

Jira: https://issues.redhat.com/browse/RHCLOUD-24119

Update app title

---

package-lock.json
package.json
src/App.tsx

https://issues.redhat.com/browse/RHCLOUD-25108

Learning resources cards filter fix (workaround)

---

.prettierrc.json
src/App.tsx
src/AppEntry.tsx
src/bootstrap.tsx

* Gets a bundle name from chrome and loads that bundle allowing the app to be used dynamically based on the quickstart bundle it needs to use.

[RHCLOUD-24573] Make bundle entrypoint dynamic

---

src/App.tsx

We want to fully use document titles in all applications. Let's use proper doc title for learning resources as well.
RHCLOUD-25356

Proper document title

---

build_deploy.sh
deploy/frontend.yml
package.json
pr_check.sh

For [RHCLOUD-25682](https://issues.redhat.com/browse/RHCLOUD-25682)

Add configs for frontend operator migration

---

deploy/frontend.yml

Learning resources was recently moved to app links, this requires adjustment of the routes and module config as well (currently failing on stage preview environment).

Adjust frontend.yml config to match what we currently have in chrome-service

---

src/App.tsx
src/components/CatalogFilter.scss
src/components/CatalogFilter.tsx

Finish up: https://issues.redhat.com/browse/RHCLOUD-25936

Fix page layout.

---

build_deploy.sh

https://www.shellcheck.net/wiki/SC2086

Use quotes to prevent globbing

---

src/App.tsx
src/components/CatalogSection.tsx
src/components/TableOfContents.tsx

Since the learning resources content can get a bit large let's add jump links that follows the user as they scroll.
https://issues.redhat.com/browse/RHCLOUD-30246

Add jump links

---

fec.config.js
package-lock.json
package.json

Since we want to showcase the learning resources widget on landing page, let's expose it as `DashboardWidget` to be consumed by chrome-service and eventually widget-layout.

Expose learning resources widget as DashboardWidget

---

fec.config.js
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesPage.tsx

https://issues.redhat.com/browse/RHCLOUD-33580

Set up global learning resources page

---

package-lock.json
package.json
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesContent.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesContent.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFiltersCategory.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesHeader.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesHeader.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesPage.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesPage.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesTabs.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesTabs.tsx
src/components/common/BookmarkIcon.scss
src/components/common/BookmarkIcon.tsx
src/utils/FiltersCategoryInterface.ts
src/utils/TabsEnum.ts
src/utils/fetchQuickstarts.ts
src/utils/toggleFavorite.ts

Built the frontend for global learning resources page. Loaded quickstart data. 
https://issues.redhat.com/browse/RHCLOUD-33582

Fill global page with all data

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesContent.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFiltersCategory.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesPage.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesTabs.tsx
src/hooks/useQuickStarts.ts
src/utils/FiltersCategoryInterface.ts
src/utils/fetchAllData.ts
src/utils/fetchFilters.ts

https://issues.redhat.com/browse/RHCLOUD-33583

Add missing tags and fetch data from new API endpoint

---

.tekton/learning-resources-pull-request.yaml
.tekton/learning-resources-push.yaml
README.md
deploy/frontend.yml

Need a test PR to check build process

Update README to test Konflux build

---

package-lock.json
package.json
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesContent.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.tsx
src/utils/fetchQuickstarts.ts
src/utils/filtersInterface.ts
src/utils/tagsEnum.ts

https://issues.redhat.com/browse/RHCLOUD-34635

Embed new tags into UI

---

src/components/LearningResourcesWidget/EmptyState.tsx
src/components/LearningResourcesWidget/LearningResourcesWidget.tsx
src/components/LearningResourcesWidget/empty-state.scss

Jira: https://issues.redhat.com/browse/RHCLOUD-33756
Depends on: https://github.com/RedHatInsights/widget-layout/pull/105

Vertically center widget Empty state

---

src/components/CatalogSection.scss

Jira: https://issues.redhat.com/browse/RHCLOUD-34535
Old
New

Fix badge color

---

src/Viewer.scss
src/Viewer.tsx
src/components/CatalogFilter.scss
src/components/CatalogHeader.scss
src/components/CatalogSection.scss
src/components/CatalogSection.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFiltersCategory.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.scss
src/components/LearningResourcesWidget/empty-state.scss
src/components/common/BookmarkIcon.scss

For [RHCLOUD-35449](https://issues.redhat.com/browse/RHCLOUD-35449). Generated with [pf-codemods](https://github.com/patternfly/pf-codemods) and [class-name-updater](https://github.com/patternfly/pf-codemods/blob/main/packages/class-name-updater/README.md).
Stage before:
Stage after:

Update classes to correct PF5 references

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.tsx
src/utils/fetchQuickstarts.ts

https://issues.redhat.com/browse/RHCLOUD-35682

Fix input handling for filtering by name

---

src/components/LearningResourcesWidget/LearningResourcesWidget.scss
src/components/LearningResourcesWidget/LearningResourcesWidget.tsx

Jira: https://issues.redhat.com/browse/RHCLOUD-35601
Old
New
Old
New

widget styling updates

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesContent.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFiltersCategory.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesHeader.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.tsx
src/utils/filtersInterface.ts

https://issues.redhat.com/browse/RHCLOUD-35571
Mocks:
https://www.figma.com/design/OMKDSoGK8br3zf2IsjhCBQ/ConsoleDot-All-Learning-Catalog?node-id=0-1&node-type=canvas&t=EBcEbOFqLfdi4p7B-0

Integrate icons into the UI

---

src/components/LearningResourcesWidget/LearningResourcesWidget.tsx

As a customer when I add bookmarked learning resources widget to landing page I see too many bookmarked items. Also when I click on quickstart it's not launching the QS and instead I am stuck on main screen.
This PR fixed both issues. First is resolved by removing redundant bookmarks filter and second is fixed by removing extra LinkWrapper plus activating correct QS and navigating to correct bundle and if present application from QS metadata.
[RHCLOUD-33179](https://issues.redhat.com/browse/RHCLOUD-33179)
[RHCLOUD-35464](https://issues.redhat.com/browse/RHCLOUD-35464)
https://github.com/user-attachments/assets/6f37ae27-9b78-410d-b6cf-f1f3d34e771d
https://github.com/user-attachments/assets/5badae78-0121-4fc4-a720-3f573c5a33eb

Fix bookmarked quickstarts by checking metadata and activating correct QS

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesContentFallback.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFiltersFallback.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesPage.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.tsx

https://issues.redhat.com/browse/RHCLOUD-35511
https://issues.redhat.com/browse/RHCLOUD-35735
Talked to UXD about the fallbacks and made the necessary changes based on their feedback.
https://www.figma.com/design/OMKDSoGK8br3zf2IsjhCBQ/ConsoleDot-All-Learning-Catalog?node-id=289-61384&node-type=frame&t=XEut3J1aukmE8o1G-0

Modify fallbacks and make quickstarts clickable

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.tsx

https://github.com/RedHatInsights/quickstarts/pull/266

Changing quick start URL

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesQuickstartItem.tsx

https://issues.redhat.com/browse/RHCLOUD-36963

Fix bookmarking bug

---

README.md

Update PF reference in README

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.tsx

https://issues.redhat.com/browse/RHCLOUD-36440

Add clear filters button

---

src/Creator.tsx
src/components/creator/CreatorPreview.scss
src/components/creator/CreatorWizard.tsx
src/components/creator/TagsSelector.tsx
src/components/creator/schema.tsx
src/components/creator/steps/common.ts
src/components/creator/steps/details.tsx

Jira ticket: https://issues.redhat.com/browse/RHCLOUD-39299
Adds a select field for the new learning resources tags.

Update quickstarts creator with tags.

---

.tekton/learning-resources-pull-request.yaml
.tekton/learning-resources-push.yaml

Attempting to fix enterprise contract failures as seen here: https://github.com/RedHatInsights/learning-resources/pull/108

Upgrade build phase of tekton pipelines for Konflux

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesContent.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFiltersMobile.tsx
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesPage.tsx
src/utils/filtersInterface.ts

https://issues.redhat.com/browse/RHCLOUD-38235
https://issues.redhat.com/browse/RHCLOUD-38236
Before:
After:

Fix alphabetical sorting interaction

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.scss
src/components/GlobalLearningResourcesPage/GlobalLearningResourcesFilters.tsx

https://issues.redhat.com/browse/RHCLOUD-38234
Before:
After:

Fix clear filters button interaction

---

.eslintrc.js
.github/workflows/test.yml
config/webpack.cy.js
cypress.config.ts
cypress/component/HelpPanel.cy.tsx
cypress/fixtures/example.json
cypress/support/commands.ts
cypress/support/component-index.html
cypress/support/component.ts
cypress/tsconfig.json
fec.config.js
package-lock.json
package.json
src/components/HelpPanel/HelpPanelContent.tsx
src/components/HelpPanel/HelpPanelCustomTabs.scss
src/components/HelpPanel/HelpPanelCustomTabs.tsx
src/components/HelpPanel/HelpPanelTabs/APIPanel.tsx
src/components/HelpPanel/HelpPanelTabs/HelpPanelTabContainer.tsx
src/components/HelpPanel/HelpPanelTabs/KBPanel.tsx
src/components/HelpPanel/HelpPanelTabs/LearnPanel.tsx
src/components/HelpPanel/HelpPanelTabs/SearchPanel.tsx
src/components/HelpPanel/HelpPanelTabs/SupportPanel.tsx
src/components/HelpPanel/HelpPanelTabs/helpPanelTabsMapper.ts
src/components/HelpPanel/index.ts

Requires https://github.com/RedHatInsights/learning-resources/pull/115 
Jira: https://issues.redhat.com/browse/RHCLOUD-37318
- added initial help panel config
- mocked API with local store
- setup initial tabs with temp content
- setup base dynamic tabs
- the button to trigger the content on global learning resources page, just for development purposes

Expose help panel module

---

src/components/TableOfContents.tsx

https://issues.redhat.com/browse/RHCLOUD-31915
This PR resolves the redirection issue to the homepage that was preventing page scrolling.

Fix jump nav link redirection

---

src/components/HelpPanel/HelpPanelContent.tsx

added component to button link
https://issues.redhat.com/browse/RHCLOUD-42345

added component to button link

---

src/components/GlobalLearningResourcesPage/GlobalLearningResourcesHeader.tsx

update image url
